## MEGA-BEZEL
default:
  # shader affects retroarch shaders
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
  # scanline affect fba2x
  scanline: true
snes:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
nes:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
n64:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
gba:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LCD-GRID
gb:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LCD-GRID
gbc:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LCD-GRID
pokemini:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LCD-GRID
fds:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
virtualboy:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LCD-GRID
nds:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__NDS
3ds:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__3DS
# Sega
sg1000:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
mastersystem:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
megadrive:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
gamegear:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LCD-GRID
sega32x:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
segacd:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
# Arcade
neogeo:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
neogeocd:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
mame:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
fba:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
naomi:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
atomiswave:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
#
ngp:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LCD-GRID
ngpc:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LCD-GRID
gw:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
vectrex:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
lynx:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LCD-GRID
lutro:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
wswan:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LCD-GRID
wswanc:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LCD-GRID
pcengine:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
pcenginecd:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
supergrafx:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
atari800:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
atari2600:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
atari5200:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
atari7800:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
prboom:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
psx:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
psp:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LCD-GRID
colecovision:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
# Computers
msx:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
msx1:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
msx2:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
amiga:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
amstradcpc:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
atarist:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
zxspectrum:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
odyssey2:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
zx81:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
pcfx:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
x68000:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LITE
