## CURVATURE
default:
  # shader affects retroarch shaders
  shader: crt/crt-lottes-fast
  # scanline affect fba2x
  scanline: true
snes:
  shader: crt/crt-lottes-fast
nes:
  shader: crt/crt-lottes-fast
n64:
  shader: crt/crt-lottes-fast
gba:
  shader: handheld/zfast-lcd
gb:
  shader: handheld/zfast-lcd
gbc:
  shader: handheld/zfast-lcd
fds:
  shader: crt/crt-lottes-fast
virtualboy:
  shader: crt/crt-lottes-fast
# Sega
sg1000:
  shader: crt/crt-lottes-fast
mastersystem:
  shader: crt/crt-lottes-fast
megadrive:
  shader: crt/crt-lottes-fast
gamegear:
  shader: handheld/zfast-lcd
sega32x:
  shader: crt/crt-lottes-fast
segacd:
  shader: crt/crt-lottes-fast
# Arcade
neogeo:
  shader: crt/crt-lottes-fast
neogeocd:
  shader: crt/crt-lottes-fast
mame:
  shader: crt/crt-lottes-fast
fba:
  shader: crt/crt-lottes-fast
naomi:
  shader: crt/crt-lottes-fast
atomiswave:
  shader: crt/crt-lottes-fast
#
ngp:
  shader: handheld/zfast-lcd
ngpc:
  shader: handheld/zfast-lcd
gw:
  shader: crt/crt-lottes-fast
vectrex:
  shader: crt/crt-lottes-fast
lynx:
  shader: handheld/zfast-lcd
lutro:
  shader: crt/crt-lottes-fast
wswan:
  shader: handheld/zfast-lcd
wswanc:
  shader: handheld/zfast-lcd
pcengine:
  shader: crt/crt-lottes-fast
pcenginecd:
  shader: crt/crt-lottes-fast
supergrafx:
  shader: crt/crt-lottes-fast
atari800:
  shader: crt/crt-lottes-fast
atari2600:
  shader: crt/crt-lottes-fast
atari5200:
  shader: crt/crt-lottes-fast
atari7800:
  shader: crt/crt-lottes-fast
prboom:
  shader: crt/crt-lottes-fast
psx:
  shader: crt/crt-lottes-fast
colecovision:
  shader: crt/crt-lottes-fast
# Computers
msx:
  shader: crt/crt-lottes-fast
msx1:
  shader: crt/crt-lottes-fast
msx2:
  shader: crt/crt-lottes-fast
amiga:
  shader: crt/crt-lottes-fast
amstradcpc:
  shader: crt/crt-lottes-fast
atarist:
  shader: crt/crt-lottes-fast
zxspectrum:
  shader: crt/crt-lottes-fast
odyssey2:
  shader: crt/crt-lottes-fast
zx81:
  shader: crt/crt-lottes-fast
pcfx:
  shader: crt/crt-lottes-fast
x68000:
  shader: crt/crt-lottes-fast
