## CURVATURE
default:
  # shader affects retroarch shaders
  shader: crt/fakelottes
  # scanline affect fba2x
  scanline: true
snes:
  shader: crt/fakelottes
nes:
  shader: crt/fakelottes
n64:
  shader: crt/fakelottes
gba:
  shader: handheld/zfast-lcd
gb:
  shader: handheld/zfast-lcd
gbc:
  shader: handheld/zfast-lcd
fds:
  shader: crt/fakelottes
virtualboy:
  shader: crt/crt-fakelottes
# Sega
sg1000:
  shader: crt/fakelottes
mastersystem:
  shader: crt/fakelottes
megadrive:
  shader: crt/fakelottes
gamegear:
  shader: handheld/zfast-lcd
sega32x:
  shader: crt/fakelottes
segacd:
  shader: crt/fakelottes
# Arcade
neogeo:
  shader: crt/fakelottes
neogeocd:
  shader: crt/fakelottes
mame:
  shader: crt/fakelottes
fba:
  shader: crt/fakelottes
naomi:
  shader: crt/fakelottes
atomiswave:
  shader: crt/fakelottes
#
ngp:
  shader: handheld/zfast-lcd
ngpc:
  shader: handheld/zfast-lcd
gw:
  shader: crt/fakelottes
vectrex:
  shader: crt/crt-fakelottes
lynx:
  shader: handheld/zfast-lcd
lutro:
  shader: crt/fakelottes
wswan:
  shader: handheld/zfast-lcd
wswanc:
  shader: handheld/zfast-lcd
pcengine:
  shader: crt/fakelottes
pcenginecd:
  shader: crt/fakelottes
supergrafx:
  shader: crt/fakelottes
atari800:
  shader: crt/fakelottes
atari2600:
  shader: crt/fakelottes
atari5200:
  shader: crt/fakelottes
atari7800:
  shader: crt/fakelottes
prboom:
  shader: crt/fakelottes
psx:
  shader: crt/fakelottes
colecovision:
  shader: crt/fakelottes
# Computers
msx:
  shader: crt/fakelottes
msx1:
  shader: crt/fakelottes
msx2:
  shader: crt/fakelottes
amiga:
  shader: crt/fakelottes
amstradcpc:
  shader: crt/fakelottes
atarist:
  shader: crt/fakelottes
zxspectrum:
  shader: crt/fakelottes
odyssey2:
  shader: crt/fakelottes
zx81:
  shader: crt/fakelottes
pcfx:
  shader: crt/fakelottes
x68000:
  shader: crt/fakelottes
