default:
  options:
    video_threaded: true
    videomode:      CEA 4 HDMI

snes:
  emulator: libretro
  core:     snes9x_next
n64:
  options:
    videomode: DMT 4 HDMI
psp:
  options:
    frameskip: true
    videomode: DMT 4 HDMI
amiga500:
  emulator: amiberry
  core:     A500
amiga1200:
  emulator: amiberry
  core:     A1200
amigacd32:
  emulator: amiberry
  core:     CD32
mastersystem:
  emulator: libretro
  core:     picodrive
megadrive:
  emulator: libretro
  core:     picodrive