n64:
  emulator: mupen64plus
  core:     gliden64
  options:
    videomode: DMT 4 HDMI
n64dd:
  emulator: mupen64plus
  core:     gliden64
  options:
    videomode: DMT 4 HDMI
psp:
  options:
    frameskip: 1
    videomode: DMT 4 HDMI
    