default:
  options:
    video_threaded: true
    ratio: "3/2"
    retroarch.video_rotation: 0 # for people upgrading
    # menu retroarch
    retroarch.menu_driver: rgui
    retroarch.menu_widget_scale_auto: "false"
    retroarch.menu_widget_scale_factor: 1.5
    resolutionIsReversed: true

n64:
  emulator: mupen64plus
  core:     glide64mk2
  options:
    ratio: "16/9"
    mupen64plus.Video-General.Rotate: 0 # for people upgrading
psp:
  options:
    frameskip: 1
    ppsspp.General.InternalScreenRotation: 0 # for people upgrading
nds:
  emulator: libretro
  core:     melonds
