default:
  emulator:
  core:
  options:
    videomode:      default
    ratio:          auto
    video_threaded: false
    smooth:         false
    rewind:         false
    bezel:          default
    forceNoBezel:   false
    shaderset:      none

