default:
  options:
    video_threaded: true
    retroarch.audio_driver: tinyalsa

psp:
  options:
    frameskip: automatic
nds:
  emulator: drastic
  core:     drastic
psx:
  emulator: libretro
  core:     duckstation
  options:
    gpu_software: true
gb:
  options:
    audio_latency: 96
gbc:
  options:
    audio_latency: 96
