default:
  options:
    video_threaded: true
    # menu retroarch
    retroarch.audio_latency:   64
    retroarch.video_hard_sync: 0
    
dreamcast:
  options:
    # menu retroarch
    # settings to fix sound issue only on Odroid XU4
    retroarch.audio_latency:   128
    retroarch.video_hard_sync: 1
n64:
  emulator: mupen64plus
  core:     glide64mk2
psp:
  options:
    frameskip: true
psx:
  options:
    # menu retroarch
    # settings to fix sound issue only on Odroid XU4
    retroarch.audio_latency:   128
    retroarch.video_hard_sync: 1
