default:
  options:
    video_threaded: true
    ratio: "3/2"
    retroarch.video_rotation: 0 # for people upgrading
    # menu retroarch
    retroarch.menu_driver: rgui
    retroarch.menu_widget_scale_auto: "false"
    retroarch.menu_widget_scale_factor: 1.5

n64:
  options:
    ratio: "16/9"
    mupen64plus.Video-General.Rotate: 0 # for people upgrading
psp:
  options:
    frameskip: automatic
    ppsspp.General.InternalScreenRotation: 0 # for people upgrading
psx:
  emulator: libretro
  core:     duckstation
  options:
    gpu_software: true
nds:
  emulator: drastic
  core:     drastic
