gamecube:
  emulator: libretro
  core:     dolphin
nds:
  emulator: libretro
  core:     melonds
wii:
  emulator: libretro
  core:     dolphin
fmtowns:
  emulator: libretro
  core:     mame
psx:
  options:
    hud_support: false # duckstation doesn't like it
ps2:
  emulator: libretro
  core:     play
flash:
  emulator: lightspark
  core:     lightspark

