default:
  options:
    video_threaded: true
    retroarch.audio_out_rate: 44100

n64:
  emulator: mupen64plus
  core:     glide64mk2
neogeocd:
  emulator: libretro
  core:     fbneo
psp:
  options:
    frameskip: true

