default:
  options:
    video_threaded: true
    # menu retroarch
    retroarch.menu_driver: rgui
    retroarch.aspect_ratio_index: 7
    retroarch.video_rotation: 1
n64:
  emulator: mupen64plus
  core: glide64mk2
  options:
    mupen64plus.Video-General.ScreenWidth: 480
    mupen64plus.Video-General.ScreenHeight: 320
    mupen64plus.Video-Glide64mk2.aspect: 2
psp:
  options:
    frameskip: true
dreamcast:
  emulator: libretro
  core: flycast
amiga500:
  emulator: amiberry
  core:     A500
amiga1200:
  emulator: amiberry
  core:     A1200
amigacd32:
  emulator: amiberry
  core:     CD32
