default:
  options:
    hud_support: true

advision:
  emulator: mame
  core:     mame
flash:
  emulator: lightspark
  core:     lightspark
fmtowns:
  emulator: libretro
  core:     mame
lcdgames:
  emulator: mame
  core:     mame
n64:
  emulator: libretro
  core:     mupen64plus-next
nds:
  emulator: libretro
  core:     melonds
ps2:
  emulator: libretro
  core:     play
tvgames:
  emulator: mame
  core:     mame
pdp1:
  emulator: mame
  core:     mame
pv1000:
  emulator: mame
  core:     mame
gamate:
  emulator: mame
  core:     mame
crvision:
  emulator: mame
  core:     mame
gamecom:
  emulator: mame
  core:     mame
fm7:
  emulator: mame
  core:     mame
gamepock:
  emulator: mame
  core:     mame
apfm1000:
  emulator: mame
  core:     mame
bbcmicro:
  emulator: mame
  core:     mame
adam:
  emulator: mame
  core:     mame
gmaster:
  emulator: mame
  core:     mame
astrocade:
  emulator: mame
  core:     mame
ti99:
  emulator: mame
  core:     mame
tutor:
  emulator: mame
  core:     mame
coco:
  emulator: mame
  core:     mame
archimedes:
  emulator: mame
  core:     mame
socrates:
  emulator: mame
  core:     mame
supracan:
  emulator: mame
  core:     mame
vsmile:
  emulator: mame
  core:     mame
xegs:
  emulator: mame
  core:     mame
atom:
  emulator: mame
  core:     mame
electron:
  emulator: mame
  core:     mame
camplynx:
  emulator: mame
  core:     mame
vgmplay:
  emulator: mame
  core:     mame
vc4000:
  emulator: mame
  core:     mame
gp32:
  emulator: mame
  core:     mame
laser310:
  emulator: mame
  core:     mame
quake3:
  emulator: vkquake3
  core:     vkquake3
saturn:
  emulator: ymir
  core:     ymir
  options:
    decorations: none
    hud_support: none
oricatmos:
  emulator: clk
  core:     clk
