default:
  options:
    hud_support: false
    video_threaded: true
    videomode: max-1280x720
    smooth:         false
    audio_latency:  96
    # menu retroarch
    retroarch.menu_driver: rgui

c64:
  emulator: libretro
  core:     vice_x64
c20:
  emulator: libretro
  core:     vice_xvic
c128:
  emulator: libretro
  core:     vice_x128
cplus4:
  emulator: libretro
  core:     vice_xplus4
pet:
  emulator: libretro
  core:     vice_xpet
scummvm:
  emulator: libretro
  core:     scummvm
