gamecube:
  emulator: libretro
  core:     dolphin
nds:
  emulator: libretro
  core:     melonds
wii:
  emulator: libretro
  core:     dolphin
fmtowns:
  emulator: libretro
  core:     mame
psx:
  options:
    hud_support: false # duckstation doesn't like it on n2+
ps2:
  emulator: libretro
  core:     play
flash:
  emulator: lightspark
  core:     lightspark
kodi:
  options:
    hud_support: false # doesn't play nice with vulkan mangohud
cdi:
  emulator: libretro
  core:     same_cdi
