default:
  options:
    video_threaded: true

n64:
  emulator: mupen64plus
  core: glide64mk2
psp:
  options:
    frameskip: true
    frameskiptype: 2
    internalresolution: 2
amiga:
  emulator: amiberry
  core:     A1200
amiga4000:
  emulator: amiberry
  core:     A4000
amigacd32:
  emulator: amiberry
  core:     CD32

