default:
  options:
    # menu retroarch
    retroarch.menu_driver: rgui

mastersystem:
  emulator: libretro
  core:     picodrive
megadrive:
  emulator: libretro
  core:     picodrive
segacd:
  emulator: libretro
  core:     picodrive
c64:
  emulator: libretro
  core:     vice_x64
