default:
  options:
    video_threaded: true

snes:
  emulator: libretro
  core:     snes9x_next
n64:
  emulator: mupen64plus
  core: glide64mk2
psp:
  options:
    frameskip: true
dreamcast:
  emulator: libretro
  core: flycast
amiga500:
  emulator: amiberry
  core:     A500
amiga1200:
  emulator: amiberry
  core:     A1200
amigacd32:
  emulator: amiberry
  core:     CD32
mastersystem:
  emulator: libretro
  core:     picodrive
megadrive:
  emulator: libretro
  core:     picodrive
