default:
  options:
    videomode:      CEA 4 HDMI
    video_threaded: true
    rewind:         false
    smooth:         false
    rewind:         false

snes:
  emulator: libretro
  core:     pocketsnes
gba:
  emulator: libretro
  core:     gpsp
mame:
  emulator: libretro
  core:     imame4all
amiga500:
  emulator: amiberry
  core:     A500
amiga500p:
  emulator: amiberry
  core:     A500P
amiga1200:
  emulator: amiberry
  core:     A1200
amiga4000:
  emulator: amiberry
  core:     A4000
amigacd32:
  emulator: amiberry
  core:     CD32
mastersystem:
  emulator: libretro
  core:     picodrive
megadrive:
  emulator: libretro
  core:     picodrive