nds:
  emulator: libretro
  core:     melonds
fmtowns:
  emulator: libretro
  core:     mame
flash:
  emulator: lightspark
  core:     lightspark
atomiswave:
  emulator: libretro
  core:     flycastvl
dreamcast:
  emulator: libretro
  core:     flycastvl
naomi:
  emulator: libretro
  core:     flycastvl