default:
  emulator:
  core:
  options:
    hud_support:    true
    videomode:      default
    ratio:          auto
    video_threaded: false
    smooth:         true
    shaderset:      sharp-bilinear-simple
    rewind:         false
    bezel:          consoles
    forceNoBezel:   false

# 0-C

3do:
  emulator: libretro
  core:     opera
3ds:
  emulator: citra
  core:     citra
abuse:
  emulator: abuse
  core:     abuse
adam:
  emulator: libretro
  core:     mess
advision:
  emulator: libretro
  core:     mess
amiga500:
  emulator: libretro
  core:     puae
amiga1200:
  emulator: libretro
  core:     puae
amigacd32:
  emulator: libretro
  core:     puae
amigacdtv:
  emulator: libretro
  core:     puae
amstradcpc:
  emulator: libretro
  core:     cap32
apfm1000:
  emulator: libretro
  core:     mess
apple2:
  emulator: gsplus
  core:     gsplus
apple2gs:
  emulator: gsplus
  core:     gsplus
arcadia:
  emulator: libretro
  core:     mess
archimedes:
  emulator: libretro
  core:     mess
astrocde:
  emulator: libretro
  core:     mess
atari2600:
  emulator: libretro
  core:     stella
atari5200:
  emulator: libretro
  core:     atari800
atari7800:
  emulator: libretro
  core:     prosystem
atari800:
  emulator: libretro
  core:     atari800
atarist:
  emulator: libretro
  core:     hatari
atom:
  emulator: libretro
  core:     mess
atomiswave:
  emulator: libretro
  core:     flycast
bbc:
  emulator: libretro
  core:     mess
c64:
  emulator: libretro
  core:     vice_x64
cplus4:
  emulator: vice
  core:     xplus4
c128:
  emulator: vice
  core:     x128
c20:
  emulator: vice
  core:     xvic
camplynx:
  emulator: libretro
  core:     mess
cannonball:
  emulator: cannonball
  core:     cannonball
cavestory:
  emulator: libretro
  core:     nxengine
cave3rd:
  emulator: demul
  core:     demul
cdi:
  emulator: libretro
  core:     mess
cdogs:
  emulator: cdogs
  core:     cdogs
cgenius:
  emulator: cgenius
  core:     cgenius
channelf:
  emulator: libretro
  core:     freechaf
coco:
  emulator: libretro
  core:     mess
colecovision:
  emulator: libretro
  core:     bluemsx
crvision:
  emulator: libretro
  core:     mess

# D-L

daphne:
  emulator: daphne
  core:     hypseus
devilutionx:
  emulator: devilutionx
  core:     devilutionx
dos:
  emulator: libretro
  core:     dosbox_pure
dreamcast:
  emulator: libretro
  core:     flycast
easyrpg:
  emulator: easyrpg
  core:     easyrpg
ecwolf:
  emulator: ecwolf
  core:     ecwolf
electron:
  emulator: libretro
  core:     mess
fbneo:
  emulator: libretro
  core:     fbneo
fds:
  emulator: libretro
  core:     fceumm
flash:
  emulator: ruffle
  core:     ruffle
  options:
    forceNoBezel: true
    hud_support: false
flatpak:
  emulator: flatpak
  core:     flatpak
  options:
    forceNoBezel: true
    hud_support: false
fm7:
  emulator: libretro
  core:     mess
fmtowns:
  emulator: tsugaru
  core:     tsugaru
gaelco:
  emulator: demul
  core:     demul
gamate:
  emulator: libretro
  core:     mess
gameandwatch:
  emulator: libretro
  core:     gw
  options:
    forceNoBezel: true
gamecom:
  emulator: libretro
  core:     mess
gamecube:
  emulator: dolphin
  core:     dolphin
gamegear:
  emulator: libretro
  core:     genesisplusgx
gamepock:
  emulator: libretro
  core:     mess
gb:
  emulator: libretro
  core:     gambatte
gb2players:
  emulator: libretro
  core:     tgbdual
gba:
  emulator: libretro
  core:     mgba
gbc:
  emulator: libretro
  core:     gambatte
gbc2players:
  emulator: libretro
  core:     tgbdual
gmaster:
  emulator: libretro
  core:     mess
gong:
  emulator: libretro
  core:     gong
gx4000:
  emulator: libretro
  core:     cap32
hikaru:
  emulator: demul
  core:     demul
intellivision:
  emulator: libretro
  core:     freeintv
jaguar:
  emulator: libretro
  core:     virtualjaguar
kodi:
  emulator: kodi
  options:
    videomode: default
lcdgames:
  emulator: libretro
  core:     gw
  options:
    forceNoBezel: true
lutro:
  emulator: libretro
  core:     lutro
lynx:
  emulator: libretro
  core:     mednafen_lynx

# M-O

macintosh:
  emulator: libretro
  core:     minivmac
mame:
  emulator: libretro
  core:     mame078plus
mastersystem:
  emulator: libretro
  core:     genesisplusgx
megadrive:
  emulator: libretro
  core:     genesisplusgx
megaduck:
  emulator: libretro
  core:     mess
model2:
  emulator: model2emu
  core:     model2emu
  options:
    forceNoBezel: true
    hud_support: false
model3:
  emulator: supermodel
  core:     supermodel
moonlight:
  emulator: moonlight
  core:     moonlight
mrboom:
  emulator: libretro
  core:     mrboom
msx1:
  emulator: libretro
  core:     bluemsx
msx2:
  emulator: libretro
  core:     bluemsx
msx2+:
  emulator: libretro
  core:     bluemsx
msxturbor:
  emulator: libretro
  core:     bluemsx
mugen:
  emulator: mugen
  core:     proton
fpinball:
  emulator: fpinball
  core:     fpinball
n64:
  emulator: mupen64plus
  core:     glide64mk2
n64dd:
  emulator: mupen64plus
  core:     glide64mk2
naomi:
  emulator: libretro
  core:     flycast
naomi2:
  emulator: libretro
  core:     flycast
nds:
  emulator: libretro
  core:     desmume
neogeo:
  emulator: libretro
  core:     fbneo
neogeocd:
  emulator: libretro
  core:     neocd
nes:
  emulator: libretro
  core:     fceumm
ngp:
  emulator: libretro
  core:     mednafen_ngp
ngpc:
  emulator: libretro
  core:     mednafen_ngp
odcommander:
  emulator: odcommander
  core:     odcommander
odyssey2:
  emulator: libretro
  core:     o2em
openbor:
  emulator: openbor
  core:     openbor6412
  options:
    # none because some games fails by default with textures (street of rage 2x)
    bezel: none

# P-S

pc88:
  emulator: libretro
  core:     quasi88
pc98:
  emulator: libretro
  core:     np2kai
pcengine:
  emulator: libretro
  core:     pce_fast
pcenginecd:
  emulator: libretro
  core:     pce_fast
pcfx:
  emulator: libretro
  core:     pcfx
pdp1:
  emulator: libretro
  core:     mess
pet:
  emulator: vice
  core:     xpet
pico8:
  emulator: libretro
  core:     retro8
plugnplay:
  emulator: libretro
  core:     mess
pokemini:
  emulator: libretro
  core:     pokemini
ports:
  emulator: sh
  core:     sh
  options:
    bezel: none
prboom:
  emulator: libretro
  core:     prboom
ps2:
  emulator: pcsx2
  core:     pcsx2
  options:
    fullboot: true
ps3:
  emulator: rpcs3
  core:     rpcs3
psp:
  emulator: ppsspp
  core: ppsspp
psx:
  emulator: libretro
  core:     pcsx_rearmed
pv1000:
  emulator: libretro
  core:     mess
pygame:
  emulator: pygame
  core:     pygame
reminiscence:
  emulator: libretro
  core:     reminiscence
samcoupe:
  emulator: samcoupe
  core:     samcoupe
satellaview:
  emulator: libretro
  core:     snes9x
saturn:
  emulator: libretro
  core:     yabasanshiro
scummvm:
  emulator: scummvm
  core:     scummvm
scv:
  emulator: libretro
  core:     emuscv
sdlpop:
  emulator: sdlpop
  core:     sdlpop
sega32x:
  emulator: libretro
  core:     picodrive
segacd:
  emulator: libretro
  core:     genesisplusgx
sg1000:
  emulator: libretro
  core:     genesisplusgx
sgb:
  emulator: libretro
  core:     mgba
socrates:
  emulator: libretro
  core:     mess
solarus:
  emulator: solarus
  core:     solarus
sonicretro:
  emulator: sonic2013
  core:     sonic2013
steam:
  emulator: steam
  core:     steam
superbroswar:
  emulator: libretro
  core:     superbroswar
sufami:
  emulator: libretro
  core:     snes9x
supracan:
  emulator: libretro
  core:     mess
snes:
  emulator: libretro
  core:     snes9x
snes-msu1:
  emulator: libretro
  core:     snes9x
supergrafx:
  emulator: libretro
  core:     mednafen_supergrafx
supervision:
  emulator: libretro
  core:     potator
switch:
  emulator: yuzu
  core:     yuzu
  options:
    forceNoBezel: true
    hud_support: false

# T-Z

thomson:
  emulator: libretro
  core:     theodore
ti99:
  emulator: libretro
  core:     mess
tic80:
  emulator: libretro
  core:     tic80
triforce:
  emulator: dolphin_triforce
  core:     dolphin_triforce
tutor:
  emulator: libretro
  core:     mess
tyrquake:
  emulator: libretro
  core:     tyrquake
uzebox:
  emulator: libretro
  core:     uzem
vc4000:
  emulator: libretro
  core:     mess
vectrex:
  emulator: libretro
  core:     vecx
vgmplay:
  emulator: libretro
  core:     mamevirtual
virtualboy:
  emulator: libretro
  core:     vb
vitaquake2:
  emulator: libretro
  core:     vitaquake2
vsmile:
  emulator: libretro
  core:     mess
wii:
  emulator: dolphin
  core:     dolphin
wiiu:
  emulator: cemu
  core:     cemu
windows:
  emulator: wine
  core:     proton
  options:
    forceNoBezel: true
    hud_support: false
windows_installers:
  emulator: wine
  core:     proton
  options:
    forceNoBezel: true
    hud_support: false
wswan:
  emulator: libretro
  core:     mednafen_wswan
wswanc:
  emulator: libretro
  core:     mednafen_wswan
x1:
  emulator: libretro
  core:     x1
x68000:
  emulator: libretro
  core:     px68k
xash3d_fwgs:
  emulator: xash3d_fwgs
  core:     xash3d_fwgs
  options:
    forceNoBezel: true
    hud_support: false
xegs:
  emulator: libretro
  core:     mess
xrick:
  emulator: libretro
  core:     xrick
xbox:
  emulator: xemu
  core:     xemu
xbox360:
  emulator: xenia
  core:     xenia
  options:
    forceNoBezel: true
    hud_support: false
zc210:
  emulator: libretro
  core:     zc210
zx81:
  emulator: libretro
  core:     '81'
zxspectrum:
  emulator: libretro
  core:     fuse
