amiga500:
  emulator: amiberry
  core:     A500
amiga1200:
  emulator: amiberry
  core:     A1200
amigacd32:
  emulator: amiberry
  core:     CD32
dos:
  emulator: dosbox
  core:     dosbox
n64:
  emulator: mupen64plus
  core:     glide64mk2
psp:
  options:
    frameskip: 1
    frameskiptype: 2
    internalresolution: 2
