default:
  options:
    video_threaded: true
    retroarch.video_rotation: 0 # for people upgrading
    # menu retroarch
    retroarch.menu_driver: rgui

n64:
  options:
    mupen64plus.Video-General.Rotate: 0 # for people upgrading
psp:
  options:
    frameskip: automatic
    ppsspp.General.InternalScreenRotation: 0 # for people upgrading
psx:
  emulator: libretro
  core:     duckstation
  options:
    gpu_software: true
nds:
  emulator: drastic
  core:     drastic
