amiga500:
  emulator: amiberry
  core:     A500
amiga1200:
  emulator: amiberry
  core:     A1200
amigacd32:
  emulator: amiberry
  core:     CD32
dos:
  emulator: dosbox
  core:     dosbox
psp:
  options:
    frameskip: automatic
    frameskiptype: 2
