default:
  options:
    video_threaded: true

n64:
  emulator: mupen64plus
  core: glide64mk2
psp:
  options:
    frameskip: true
neogeocd:
  emulator: libretro
  core:     fbneo
amiga500:
  emulator: libretro
  core:     puae
amiga1200:
  emulator: libretro
  core:     puae
amigacd32:
  emulator: libretro
  core:     puae
amigacdtv:
  emulator: libretro
  core:     puae
