default:
  options:
    hud_support: true

nds:
  emulator: drastic
  core:     drastic
3ds:
  emulator: azahar
  core:     azahar
flash:
  emulator: lightspark
  core:     lightspark
fmtowns:
  emulator: libretro
  core:     mame
model3:
  emulator: supermodel
  core:     supermodel-legacy
  options:
    videomode: max-1920x1080
scummvm:
  emulator: scummvm
  core:     scummvm
  options:
    decorations: none
    hud_support: none
quake3:
  emulator: vkquake3
  core:     vkquake3
  options:
    videomode: max-1920x1080
    decorations: none
    hud_support: none
gamecube:
  emulator: dolphin
  core:     dolphin
wii:
  emulator: dolphin
  core:     dolphin
  options:
    gfxbackend: Vulkan
