nds:
  emulator: drastic
  core:     drastic
fmtowns:
  emulator: libretro
  core:     mame
flash:
  emulator: lightspark
  core:     lightspark
atomiswave:
  emulator: flycast
  core:     flycast
dreamcast:
  emulator: flycast
  core:     flycast
naomi:
  emulator: flycast
  core:     flycast
naomi2:
  emulator: flycast
  core:     flycast
systemsp:
  emulator: flycast
  core:     flycast
cdi:
  emulator: libretro
  core:     same_cdi
