default:
  options:
    video_threaded: true
    # menu retroarch
    retroarch.audio_latency:   64
    retroarch.video_hard_sync: 0
    
n64:
  emulator: mupen64plus
  core: glide64mk2
psp:
  options:
    frameskip: true
amiga500:
  emulator: amiberry
  core:     A500
amiga1200:
  emulator: amiberry
  core:     A1200
amigacd32:
  emulator: amiberry
  core:     CD32
psx:
  options:
    # menu retroarch
    # settings to fix sound issue only on Odroid XU4
    retroarch.audio_latency:   128
    retroarch.video_hard_sync: 1
