default:
  options:
    video_threaded: true
    # rotation
    retroarch.aspect_ratio_index: 21
    retroarch.video_rotation: 1

n64:
  emulator: mupen64plus
  core: glide64mk2
  options:
    # rotation
    mupen64plus.Video-General.Rotate: 1
    mupen64plus.Video-Glide64mk2.aspect: 2
psp:
  options:
    frameskip: true
    ppsspp.General.InternalScreenRotation: 2
dreamcast:
  options:
    reicast.config.rend.Rotate90: yes
amiga:
  emulator: amiberry
  core:     A1200
amigacd32:
  emulator: amiberry
  core:     CD32
lynx:
  emulator: libretro
  core:     handy
