default:
  options:
    video_threaded: true
n64:
  emulator: mupen64plus
  core: glide64mk2
amiga500:
  emulator: amiberry
  core:     A500
amiga1200:
  emulator: amiberry
  core:     A1200
amigacd32:
  emulator: amiberry
  core:     CD32
