default:
  options:
    videomode:      CEA 4 HDMI
    video_threaded: true
    smooth:         false
    
amiga500:
  emulator: amiberry
  core:     A500
amiga1200:
  emulator: amiberry
  core:     A1200
amigacd32:
  emulator: amiberry
  core:     CD32
dos:
  emulator: dosbox
  core:     dosbox
gba:
  emulator: libretro
  core:     gpsp
mame:
  emulator: libretro
  core:     imame4all
mastersystem:
  emulator: libretro
  core:     picodrive
megadrive:
  emulator: libretro
  core:     picodrive
snes:
  emulator: libretro
  core:     pocketsnes
c64:
  emulator: vice
  core:     x64
c128:
  emulator: vice
  core:     x128
c20:
  emulator: vice
  core:     xvic
pet:
  emulator: vice
  core:     xpet
cplus4:
  emulator: vice
  core:     xplus4

