default:
  options:
    retroarch.audio_out_rate: 44100

dos:
  emulator: dosbox
  core:     dosbox
mastersystem:
  emulator: libretro
  core:     picodrive
megadrive:
  emulator: libretro
  core:     picodrive
n64:
  emulator: mupen64plus
  core:     glide64mk2
psp:
  options:
    frameskip: 1
snes:
  emulator: libretro
  core:     snes9x_next
