## SCANLINES
default:
  # shader affects retroarch shaders
  shader: crt/crt-pi
  # scanline affect fba2x
  scanline: true
snes:
  shader: crt/crt-pi
nes:
  shader: crt/crt-pi
n64:
  shader: crt/crt-pi
gba:
  shader: handheld/lcd-grid-v2
gb:
  shader: handheld/lcd-grid-v2
gbc:
  shader: handheld/lcd-grid-v2
fds:
  shader: crt/crt-pi
virtualboy:
  shader: crt/crt-pi
# Sega
sg1000:
  shader: crt/crt-pi
mastersystem:
  shader: crt/crt-pi
megadrive:
  shader: crt/crt-pi
gamegear:
  shader: handheld/lcd-grid-v2
sega32x:
  shader: crt/crt-pi
segacd:
  shader: crt/crt-pi
# Arcade
neogeo:
  shader: crt/crt-pi
neogeocd:
  shader: crt/crt-pi
mame:
  shader: crt/crt-pi
fba:
  shader: crt/crt-pi
naomi:
  shader: crt/crt-pi
atomiswave:
  shader: crt/crt-pi
#
ngp:
  shader: handheld/lcd-grid-v2
ngpc:
  shader: handheld/lcd-grid-v2
gw:
  shader: crt/crt-pi
vectrex:
  shader: crt/crt-pi
lynx:
  shader: handheld/lcd-grid-v2
lutro:
  shader: crt/crt-pi
wswan:
  shader: handheld/lcd-grid-v2
wswanc:
  shader: handheld/lcd-grid-v2
pcengine:
  shader: crt/crt-pi
pcenginecd:
  shader: crt/crt-pi
supergrafx:
  shader: crt/crt-pi
atari800:
  shader: crt/crt-pi
atari2600:
  shader: crt/crt-pi
atari5200:
  shader: crt/crt-pi
atari7800:
  shader: crt/crt-pi
prboom:
  shader: crt/crt-pi
psx:
  shader: crt/crt-pi
colecovision:
  shader: crt/crt-pi
# Computers
msx:
  shader: crt/crt-pi
msx1:
  shader: crt/crt-pi
msx2:
  shader: crt/crt-pi
amiga:
  shader: crt/crt-pi
amstradcpc:
  shader: crt/crt-pi
atarist:
  shader: crt/crt-pi
zxspectrum:
  shader: crt/crt-pi
odyssey2:
  shader: crt/crt-pi
zx81:
  shader: crt/crt-pi
pcfx:
  shader: crt/crt-pi
x68000:
  shader: crt/crt-pi
