## SCANLINES
default:
  # shader affects retroarch shaders
  shader: crt/crt-pi
  # scanline affect fba2x
  scanline: true
snes:
  shader: crt/crt-pi
nes:
  shader: crt/crt-pi
n64:
  shader: interpolation/sharp-bilinear-scanlines
gba:
  shader: handheld/lcd-grid-v2
gb:
  shader: handheld/lcd-grid-v2
gbc:
  shader: handheld/lcd-grid-v2
fds:
  shader: interpolation/sharp-bilinear-scanlines
virtualboy:
  shader: interpolation/sharp-bilinear-scanlines
# Sega
sg1000:
  shader: interpolation/sharp-bilinear-scanlines
mastersystem:
  shader: crt/crt-pi
megadrive:
  shader: crt/crt-pi
gamegear:
  shader: handheld/lcd-grid-v2
sega32x:
  shader: crt/crt-pi
segacd:
  shader: interpolation/sharp-bilinear-scanlines
# Arcade
neogeo:
  shader: interpolation/sharp-bilinear-scanlines
neogeocd:
  shader: interpolation/sharp-bilinear-scanlines
mame:
  shader: interpolation/sharp-bilinear-scanlines
hbmame:
  shader: interpolation/sharp-bilinear-scanlines
fba:
  shader: interpolation/sharp-bilinear-scanlines
naomi:
  shader: interpolation/sharp-bilinear-scanlines
atomiswave:
  shader: interpolation/sharp-bilinear-scanlines
#
ngp:
  shader: handheld/lcd-grid-v2
ngpc:
  shader: handheld/lcd-grid-v2
gw:
  shader: crt/crt-pi
vectrex:
  shader: crt/crt-pi
lynx:
  shader: handheld/lcd-grid-v2
lutro:
  shader: interpolation/sharp-bilinear-scanlines
wswan:
  shader: handheld/lcd-grid-v2
wswanc:
  shader: handheld/lcd-grid-v2
pcengine:
  shader: crt/crt-pi
pcenginecd:
  shader: crt/crt-pi
supergrafx:
  shader: crt/crt-pi
atari800:
  shader: interpolation/sharp-bilinear-scanlines
atari2600:
  shader: interpolation/sharp-bilinear-scanlines
atari5200:
  shader: interpolation/sharp-bilinear-scanlines
atari7800:
  shader: interpolation/sharp-bilinear-scanlines
prboom:
  shader: crt/crt-pi
psx:
  shader: crt/crt-pi
colecovision:
  shader: crt/crt-pi
# Computers
msx:
  shader: interpolation/sharp-bilinear-scanlines
msx1:
  shader: interpolation/sharp-bilinear-scanlines
msx2:
  shader: interpolation/sharp-bilinear-scanlines
amiga:
  shader: crt/crt-pi
amstradcpc:
  shader: crt/crt-pi
atarist:
  shader: crt/crt-pi
zxspectrum:
  shader: interpolation/sharp-bilinear-scanlines
odyssey2:
  shader: interpolation/sharp-bilinear-scanlines
zx81:
  shader: interpolation/sharp-bilinear-scanlines
pcfx:
  shader: interpolation/sharp-bilinear-scanlines
x68000:
  shader: interpolation/sharp-bilinear-scanlines
